#!/usr/bin/env bash
#This script instals nginx web server

apt-get update -y -qq && \
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
