#!/usr/bin/env bash
# script displays "To infinity and beyond" indefinitely
# script sleeps for 2 secs in between each iteration
# script displays "I am invincible!!!" when receiving a SIGTERM signal

function signal_handler {
	echo "I am invincible!!!"
}
trap 'signal_handler' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
