#!/usr/bin/env bash
# script displays numbers from 1 to 100
# script displays "FizzBuzz" when number is a multiple of 3 and 5
# displays "Fizz" when number is a multiple of 3
# displays "Buzz" when number is a multiple of 5
# otherwise, displays the number

for i in {1..100}
do
	if (( i % 3 == 0 )) && (( i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $i
	fi
done
