#!/usr/bin/env bash
# This script relays information about a file

FILES="school"

if [ -e "$FILES" ]
then
	echo "school file exists"
	if [ ! -s "$FILES" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$FILES" ]
	then
		echo "school is a regular  file"
	fi
else
	echo "school file does not exist"
fi
